// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var PfIcon = require("../../../packages/pf-icon/src/PfIcon.bs.js");
var ArrayUtils = require("../../../shared/utils/ArrayUtils.bs.js");
var MarkdownEditor = require("../../../shared/components/MarkdownEditor.bs.js");
var CoursesReview__Checklist = require("./CoursesReview__Checklist.bs.js");

function str(prim) {
  return prim;
}

function CoursesReview__FeedbackEditor(Props) {
  var feedback = Props.feedback;
  var updateFeedbackCB = Props.updateFeedbackCB;
  var label = Props.label;
  var reviewChecklist = Props.reviewChecklist;
  var updateReviewChecklistCB = Props.updateReviewChecklistCB;
  var checklistVisible = Props.checklistVisible;
  var targetId = Props.targetId;
  var match = React.useState((function () {
          return checklistVisible;
        }));
  var setChecklistVisible = match[1];
  var reviewChecklistIsNotEmpty = ArrayUtils.isNotEmpty(reviewChecklist);
  var tmp;
  var exit = 0;
  if (match[0] || !reviewChecklistIsNotEmpty) {
    exit = 1;
  } else {
    tmp = React.createElement("div", {
          className: "px-4 pt-4 md:px-6 pt-6"
        }, React.createElement("button", {
              className: "flex items-center bg-gray-100 border p-4 rounded-lg w-full text-left text-primary-500 font-semibold hover:bg-gray-200 hover:border-primary-300 focus:outline-none",
              onClick: (function (param) {
                  return Curry._1(setChecklistVisible, (function (param) {
                                return true;
                              }));
                })
            }, React.createElement("span", {
                  className: "inline-flex w-10 h-10 border border-white items-center justify-center rounded-full bg-primary-100 text-primary-500"
                }, React.createElement("i", {
                      className: "fas fa-list"
                    })), React.createElement("span", {
                  className: "ml-3"
                }, "Show Review Checklist")));
  }
  if (exit === 1) {
    tmp = React.createElement(CoursesReview__Checklist.make, {
          reviewChecklist: reviewChecklist,
          updateFeedbackCB: updateFeedbackCB,
          feedback: feedback,
          updateReviewChecklistCB: updateReviewChecklistCB,
          targetId: targetId
        });
  }
  return React.createElement("div", undefined, React.createElement("div", undefined, tmp), React.createElement("div", {
                  className: "px-4 pt-4 md:px-6 md:pt-6 course-review__feedback-editor text-sm"
                }, React.createElement("h5", {
                      className: "font-semibold text-sm flex items-center"
                    }, React.createElement(PfIcon.make, {
                          className: "if i-comment-alt-regular text-gray-800 text-base md:text-lg inline-block"
                        }), React.createElement("span", {
                          className: "ml-2 md:ml-3 tracking-wide"
                        }, label)), React.createElement("div", {
                      "aria-label": "feedback",
                      className: "mt-2 md:ml-7"
                    }, React.createElement(MarkdownEditor.make, {
                          value: feedback,
                          onChange: updateFeedbackCB,
                          profile: /* Permissive */2,
                          maxLength: 10000,
                          placeholder: "This feedback will be emailed to students when you finish grading."
                        }))));
}

var make = CoursesReview__FeedbackEditor;

exports.str = str;
exports.make = make;
/* react Not a pure module */
