// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ArrayUtils = require("../../../shared/utils/ArrayUtils.bs.js");
var SubmissionChecklistItemShow = require("./SubmissionChecklistItemShow.bs.js");

function str(prim) {
  return prim;
}

function SubmissionChecklistShow(Props) {
  var checklist = Props.checklist;
  var updateChecklistCB = Props.updateChecklistCB;
  var pending = Props.pending;
  return React.createElement("div", undefined, ArrayUtils.isEmpty(checklist) ? React.createElement("div", undefined, "Target was marked as complete.") : $$Array.mapi((function (index, checklistItem) {
                      return React.createElement(SubmissionChecklistItemShow.make, {
                                  index: index,
                                  checklistItem: checklistItem,
                                  updateChecklistCB: updateChecklistCB,
                                  checklist: checklist,
                                  pending: pending,
                                  key: String(index)
                                });
                    }), checklist));
}

var make = SubmissionChecklistShow;

exports.str = str;
exports.make = make;
/* react Not a pure module */
