// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pluralize = require("pluralize");

function pluralize(word, countOpt, inclusiveOpt, param) {
  var count = countOpt !== undefined ? countOpt : 2;
  var inclusive = inclusiveOpt !== undefined ? inclusiveOpt : false;
  return Pluralize(word, count, inclusive);
}

exports.pluralize = pluralize;
/* pluralize Not a pure module */
