// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Course = /* alias */0;

var Community = /* alias */0;

var Connection = /* alias */0;

exports.Course = Course;
exports.Community = Community;
exports.Connection = Connection;
/* No side effect */
