// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var DateFns = require("../../../shared/utils/DateFns.bs.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var SubmissionChecklistItem = require("../../review/types/SubmissionChecklistItem.bs.js");

var UnexpectedStatusValue = Caml_exceptions.create("CoursesCurriculum__Submission.UnexpectedStatusValue");

function id(t) {
  return t.id;
}

function createdAt(t) {
  return t.createdAt;
}

function status(t) {
  return t.status;
}

function checklist(t) {
  return t.checklist;
}

function pending(t) {
  var match = t.status;
  return match === 1;
}

function createdAtPretty(t) {
  return DateFns.format(t.createdAt, "MMMM d, yyyy");
}

function sort(ts) {
  return Belt_List.sort(ts, (function (t1, t2) {
                return DateFns.differenceInSeconds(t1.createdAt, t2.createdAt);
              }));
}

function decode(json) {
  var unknownValue = Json_decode.field("status", Json_decode.string, json);
  var tmp;
  switch (unknownValue) {
    case "failed" :
        tmp = /* Failed */3;
        break;
    case "marked_as_complete" :
        tmp = /* MarkedAsComplete */0;
        break;
    case "passed" :
        tmp = /* Passed */2;
        break;
    case "pending" :
        tmp = /* Pending */1;
        break;
    default:
      throw [
            UnexpectedStatusValue,
            unknownValue
          ];
  }
  var partial_arg = Json_decode.field("files", (function (param) {
          return Json_decode.array(SubmissionChecklistItem.decodeFile, param);
        }), json);
  var partial_arg$1 = function (param) {
    return SubmissionChecklistItem.decode(partial_arg, param);
  };
  return {
          id: Json_decode.field("id", Json_decode.string, json),
          createdAt: Json_decode.field("createdAt", DateFns.decodeISO, json),
          status: tmp,
          checklist: Json_decode.field("checklist", (function (param) {
                  return Json_decode.array(partial_arg$1, param);
                }), json)
        };
}

function make(id, createdAt, status, checklist) {
  return {
          id: id,
          createdAt: createdAt,
          status: status,
          checklist: checklist
        };
}

exports.UnexpectedStatusValue = UnexpectedStatusValue;
exports.id = id;
exports.createdAt = createdAt;
exports.status = status;
exports.checklist = checklist;
exports.pending = pending;
exports.createdAtPretty = createdAtPretty;
exports.sort = sort;
exports.decode = decode;
exports.make = make;
/* DateFns Not a pure module */
