// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Topic = /* alias */0;

var Post = /* alias */0;

var LinkedTarget = /* alias */0;

var Community = /* alias */0;

exports.Topic = Topic;
exports.Post = Post;
exports.LinkedTarget = LinkedTarget;
exports.Community = Community;
/* No side effect */
