// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function decode(json) {
  return {
          id: Caml_option.null_to_opt(Json_decode.field("id", (function (param) {
                      return Json_decode.nullable(Json_decode.string, param);
                    }), json)),
          title: Json_decode.field("title", Json_decode.string, json)
        };
}

function id(t) {
  return t.id;
}

function title(t) {
  return t.title;
}

exports.decode = decode;
exports.id = id;
exports.title = title;
/* No side effect */
