// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Level = /* alias */0;

var DistributionInLevel = /* alias */0;

var Course = /* alias */0;

var Coach = /* alias */0;

var Teams = /* alias */0;

var TeamInfo = /* alias */0;

var StudentDetails = /* alias */0;

var Submission = /* alias */0;

var Submissions = /* alias */0;

var CoachNote = /* alias */0;

exports.Level = Level;
exports.DistributionInLevel = DistributionInLevel;
exports.Course = Course;
exports.Coach = Coach;
exports.Teams = Teams;
exports.TeamInfo = TeamInfo;
exports.StudentDetails = StudentDetails;
exports.Submission = Submission;
exports.Submissions = Submissions;
exports.CoachNote = CoachNote;
/* No side effect */
