// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var DisablingCover = require("../shared/components/DisablingCover.bs.js");
var HomeStyleguide__MarkdownSyntaxHighlightingPreview = require("../home/styleguide/HomeStyleguide__MarkdownSyntaxHighlightingPreview.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(HomeStyleguide__MarkdownSyntaxHighlightingPreview.make, { }), "styleguide__markdown-syntax-highlighting-root");

function stringRepeat(n, s) {
  return $$String.concat("", $$Array.to_list(Caml_array.caml_make_vect(n, s)));
}

ReactDOMRe.renderToElementWithId(React.createElement(DisablingCover.make, {
          disabled: true,
          message: "This element is disabled, and this is a custom message.",
          children: React.createElement("div", {
                className: "m-2 p-2 border-2 border-red-500"
              }, stringRepeat(10, "This is the element being disabled. "))
        }), "styleguide__disabling-cover-root");

exports.stringRepeat = stringRepeat;
/*  Not a pure module */
