// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var DomUtils = require("../shared/utils/DomUtils.bs.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var CourseCoaches__Root = require("../schools/courses/components/CourseCoaches__Root.bs.js");
var CourseCoaches__CourseCoach = require("../schools/courses/types/course_coaches/CourseCoaches__CourseCoach.bs.js");
var CourseCoaches__SchoolCoach = require("../schools/courses/types/course_coaches/CourseCoaches__SchoolCoach.bs.js");

function decodeProps(json) {
  return {
          courseCoaches: Json_decode.field("courseCoaches", (function (param) {
                  return Json_decode.array(CourseCoaches__CourseCoach.decode, param);
                }), json),
          schoolCoaches: Json_decode.field("schoolCoaches", (function (param) {
                  return Json_decode.array(CourseCoaches__SchoolCoach.decode, param);
                }), json),
          authenticityToken: Json_decode.field("authenticityToken", Json_decode.string, json),
          courseId: Json_decode.field("courseId", Json_decode.string, json)
        };
}

var props = decodeProps(DomUtils.parseJSONTag("course-coaches__props", /* () */0));

ReactDOMRe.renderToElementWithId(React.createElement(CourseCoaches__Root.make, {
          courseCoaches: props.courseCoaches,
          schoolCoaches: props.schoolCoaches,
          courseId: props.courseId,
          authenticityToken: props.authenticityToken
        }), "sa-coaches-enrollment-panel");

exports.decodeProps = decodeProps;
exports.props = props;
/* props Not a pure module */
