// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Course = /* alias */0;

var EvaluationCriteria = /* alias */0;

var Level = /* alias */0;

var TargetGroup = /* alias */0;

var Target = /* alias */0;

var AnswerOption = /* alias */0;

var QuizQuestion = /* alias */0;

var TargetDetails = /* alias */0;

var Version = /* alias */0;

var ChecklistItem = /* alias */0;

exports.Course = Course;
exports.EvaluationCriteria = EvaluationCriteria;
exports.Level = Level;
exports.TargetGroup = TargetGroup;
exports.Target = Target;
exports.AnswerOption = AnswerOption;
exports.QuizQuestion = QuizQuestion;
exports.TargetDetails = TargetDetails;
exports.Version = Version;
exports.ChecklistItem = ChecklistItem;
/* No side effect */
