// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Team = /* alias */0;

var Student = /* alias */0;

var Coach = /* alias */0;

var StudentInfo = /* alias */0;

var Level = /* alias */0;

var Page = /* alias */0;

var Filter = /* alias */0;

var SelectedStudent = /* alias */0;

exports.Team = Team;
exports.Student = Student;
exports.Coach = Coach;
exports.StudentInfo = StudentInfo;
exports.Level = Level;
exports.Page = Page;
exports.Filter = Filter;
exports.SelectedStudent = SelectedStudent;
/* No side effect */
