// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var OptionUtils = require("../../../../shared/utils/OptionUtils.bs.js");

function name(t) {
  return t.name;
}

function id(t) {
  return t.id;
}

function students(t) {
  return t.students;
}

function makeFromJS(teamData) {
  return {
          id: teamData.id,
          name: teamData.name,
          students: $$Array.map((function (student) {
                  return student.name;
                }), teamData.students)
        };
}

function makeArrayFromJs(detailsOfTeams) {
  return Belt_Array.keepMap(detailsOfTeams, (function (param) {
                return OptionUtils.map(makeFromJS, param);
              }));
}

function decode(json) {
  return {
          id: Json_decode.field("id", Json_decode.string, json),
          name: Json_decode.field("name", Json_decode.string, json),
          students: Json_decode.field("students", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), json)
        };
}

exports.name = name;
exports.id = id;
exports.students = students;
exports.makeFromJS = makeFromJS;
exports.makeArrayFromJs = makeArrayFromJs;
exports.decode = decode;
/* No side effect */
