// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ContentBlock = require("../../../../shared/types/ContentBlock.bs.js");

function str(prim) {
  return prim;
}

function onChange(contentBlock, updateContentBlockCB, $$event) {
  $$event.preventDefault();
  var newCaption = $$event.target.value;
  return Curry._1(updateContentBlockCB, ContentBlock.updateImage(newCaption, contentBlock));
}

function CurriculumEditor__ImageBlockEditor(Props) {
  var url = Props.url;
  var caption = Props.caption;
  var contentBlock = Props.contentBlock;
  var updateContentBlockCB = Props.updateContentBlockCB;
  var captionInputId = "caption-" + ContentBlock.id(contentBlock);
  var tmp = caption === "" ? null : React.createElement("div", {
          className: "px-4 py-2 text-sm italic text-center"
        }, caption);
  return React.createElement("div", {
              className: "relative border border-gray-400 rounded-lg"
            }, React.createElement("div", {
                  className: "content-block__content text-base bg-gray-200 flex justify-center items-center rounded-t-lg"
                }, React.createElement("div", {
                      className: "w-full"
                    }, React.createElement("div", {
                          className: "rounded-t-lg bg-white"
                        }, React.createElement("img", {
                              className: "mx-auto",
                              alt: caption,
                              src: url
                            }), tmp))), React.createElement("div", {
                  className: "flex border-t justify-end"
                }, React.createElement("div", {
                      className: "flex-1 content-block__action-bar-input p-3"
                    }, React.createElement("label", {
                          className: "text-sm font-semibold",
                          htmlFor: captionInputId
                        }, "Caption"), React.createElement("span", {
                          className: "text-sm ml-1"
                        }, "(optional)"), React.createElement("input", {
                          className: "mt-1 appearance-none block w-full h-10 bg-white text-gray-800 border rounded py-3 px-3 focus:border-gray-400 leading-tight focus:outline-none focus:bg-white focus:border-gray",
                          id: captionInputId,
                          maxLength: 250,
                          placeholder: "A caption for the image",
                          type: "text",
                          value: caption,
                          onChange: (function (param) {
                              return onChange(contentBlock, updateContentBlockCB, param);
                            })
                        }))));
}

var make = CurriculumEditor__ImageBlockEditor;

exports.str = str;
exports.onChange = onChange;
exports.make = make;
/* react Not a pure module */
