// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Link = require("../../../../shared/components/Link.bs.js");
var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ListUtils = require("../../../../shared/utils/ListUtils.bs.js");
var CurriculumEditor__Course = require("../../types/curriculum_editor/CurriculumEditor__Course.bs.js");
var CurriculumEditor__Target = require("../../types/curriculum_editor/CurriculumEditor__Target.bs.js");
var CurriculumEditor__SortResourcesMutation = require("../../utils/curriculum_editor/CurriculumEditor__SortResourcesMutation.bs.js");

((require("./CurriculumEditor__TargetShow.css")));

function str(prim) {
  return prim;
}

function targetClasses(target, targets) {
  var match = List.length(targets) === 1;
  var match$1 = CurriculumEditor__Target.visibility(target);
  return "target-group__target flex justify-between items-center pl-2 pr-5 " + (
          match ? (
              match$1 >= 2 ? "target-group__target--archived py-4 pl-5" : "py-6 pl-5"
            ) : (
              match$1 >= 2 ? "target-group__target--archived py-4" : "py-6"
            )
        );
}

function updateSortIndex(targets, target, up, updateTargetSortIndexCB) {
  var newTargets = ListUtils.swap(up, target, targets);
  var targetIds = $$Array.of_list(List.map(CurriculumEditor__Target.id, newTargets));
  CurriculumEditor__SortResourcesMutation.sort(/* Target */0, targetIds);
  return Curry._1(updateTargetSortIndexCB, newTargets);
}

function sortIndexHiddenClass(bool) {
  if (bool) {
    return " invisible";
  } else {
    return "";
  }
}

function editorLink(linkPrefix, linkSuffix, target, iconClass) {
  var link = linkPrefix + linkSuffix;
  return React.createElement(Link.make, {
              href: link,
              className: "curriculum-editor__target-show-quick-link text-gray-400 border-l border-transparent py-6 px-3 hover:bg-gray-200",
              title: "Edit " + (linkSuffix + (" of target " + CurriculumEditor__Target.title(target))),
              children: React.createElement("i", {
                    className: "fas fa-fw " + iconClass
                  })
            });
}

function CurriculumEditor__TargetShow(Props) {
  var target = Props.target;
  var targets = Props.targets;
  var updateTargetSortIndexCB = Props.updateTargetSortIndexCB;
  var index = Props.index;
  var course = Props.course;
  var linkPrefix = "/school/courses/" + (CurriculumEditor__Course.id(course) + ("/targets/" + (CurriculumEditor__Target.id(target) + "/")));
  var tmp;
  if (List.length(targets) === 1) {
    tmp = null;
  } else {
    var bool = (index + 1 | 0) === List.length(targets);
    tmp = React.createElement("div", {
          className: "target-group__target-reorder relative flex flex-col z-10 h-full border-r border-transparent text-gray-700 justify-between items-center"
        }, React.createElement("div", {
              className: "target-group__target-reorder-up flex items-center justify-center cursor-pointer w-9 h-9 p-1 text-gray-400 hover:bg-gray-200" + (
                index === 0 ? " invisible" : ""
              ),
              id: "target-move-up-" + CurriculumEditor__Target.id(target),
              title: "Move Up",
              onClick: (function (param) {
                  return updateSortIndex(targets, target, true, updateTargetSortIndexCB);
                })
            }, React.createElement("i", {
                  className: "fas fa-arrow-up text-sm"
                })), React.createElement("div", {
              className: "target-group__target-reorder-down flex items-center justify-center cursor-pointer w-9 h-9 p-1 border-t border-transparent text-gray-400 hover:bg-gray-200" + (
                bool ? " invisible" : ""
              ),
              id: "target-move-down-" + CurriculumEditor__Target.id(target),
              title: "Move Down",
              onClick: (function (param) {
                  return updateSortIndex(targets, target, false, updateTargetSortIndexCB);
                })
            }, React.createElement("i", {
                  className: "fas fa-arrow-down text-sm"
                })));
  }
  var match = CurriculumEditor__Target.visibility(target);
  return React.createElement("div", {
              className: "flex target-group__target-container border-t bg-white overflow-hidden relative hover:bg-gray-100 hover:text-primary-500"
            }, tmp, React.createElement(Link.make, {
                  href: linkPrefix + "content",
                  className: targetClasses(target, targets),
                  id: "target-show-" + CurriculumEditor__Target.id(target),
                  title: "Edit content of target " + CurriculumEditor__Target.title(target),
                  children: null
                }, React.createElement("p", {
                      className: "font-semibold text-sm"
                    }, CurriculumEditor__Target.title(target)), React.createElement("div", {
                      className: "items-center"
                    }, match !== 0 ? null : React.createElement("span", {
                            className: "target-group__target-draft-pill leading-tight text-xs py-1 px-2 font-semibold rounded-lg border bg-blue-100 text-blue-700 border-blue-400 mr-2 whitespace-no-wrap"
                          }, React.createElement("i", {
                                className: "fas fa-file-signature text-sm"
                              }), React.createElement("span", {
                                className: "ml-1"
                              }, "Draft")))), editorLink(linkPrefix, "details", target, "fa-list-alt"), editorLink(linkPrefix, "versions", target, "fa-code-branch"));
}

var make = CurriculumEditor__TargetShow;

exports.str = str;
exports.targetClasses = targetClasses;
exports.updateSortIndex = updateSortIndex;
exports.sortIndexHiddenClass = sortIndexHiddenClass;
exports.editorLink = editorLink;
exports.make = make;
/*  Not a pure module */
