// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function test(value, url) {
  var tester = new RegExp(value);
  return tester.test(url);
}

function iconClass(url) {
  if (test("twitter", url)) {
    return "fab fa-twitter";
  } else if (test("facebook", url)) {
    return "fab fa-facebook-f";
  } else if (test("instagram", url)) {
    return "fab fa-instagram";
  } else if (test("youtube", url)) {
    return "fab fa-youtube";
  } else if (test("linkedin", url)) {
    return "fab fa-linkedin";
  } else if (test("snapchat", url)) {
    return "fab fa-snapchat";
  } else if (test("tumblr", url)) {
    return "fab fa-tumblr";
  } else if (test("pinterest", url)) {
    return "fab fa-pinterest";
  } else if (test("reddit", url)) {
    return "fab fa-reddit";
  } else if (test("flickr", url)) {
    return "fab fa-flickr";
  } else {
    return "fas fa-users";
  }
}

function SchoolCustomize__SocialLink(Props) {
  var url = Props.url;
  return React.createElement("div", {
              className: "h-8 w-8 mr-2 mt-2 flex items-center justify-center"
            }, React.createElement("i", {
                  className: "text-xl " + iconClass(url)
                }));
}

var make = SchoolCustomize__SocialLink;

exports.test = test;
exports.iconClass = iconClass;
exports.make = make;
/* react Not a pure module */
