// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var School__InputGroupError = require("../../shared/components/School__InputGroupError.bs.js");

function str(prim) {
  return prim;
}

function imageLabel(imageName, selectedImageName) {
  if (selectedImageName !== undefined) {
    return React.createElement("span", undefined, "You have selected ", React.createElement("code", {
                    className: "mr-1"
                  }, selectedImageName), " to replace the current image.");
  } else if (imageName !== undefined) {
    return React.createElement("span", undefined, "Please pick a file to replace " + imageName);
  } else {
    return "Please choose an image file to customize";
  }
}

function SchoolCustomize__ImageFileInput(Props) {
  var id = Props.id;
  var disabled = Props.disabled;
  var name = Props.name;
  var onChange = Props.onChange;
  var labelText = Props.labelText;
  var imageName = Props.imageName;
  var selectedImageName = Props.selectedImageName;
  var errorState = Props.errorState;
  var errorMessageOpt = Props.errorMessage;
  var errorMessage = errorMessageOpt !== undefined ? errorMessageOpt : "must be a JPEG / PNG under 2 MB in size";
  return React.createElement("div", {
              key: id,
              className: "mt-4"
            }, React.createElement("label", {
                  className: "block tracking-wide text-gray-800 text-xs font-semibold",
                  htmlFor: id
                }, labelText), React.createElement("input", {
                  className: "hidden",
                  id: id,
                  accept: ".jpg,.jpeg,.png,.gif,image/x-png,image/gif,image/jpeg",
                  disabled: disabled,
                  multiple: false,
                  name: name,
                  required: false,
                  type: "file",
                  onChange: onChange
                }), React.createElement("label", {
                  className: "file-input-label mt-2",
                  htmlFor: id
                }, React.createElement("i", {
                      className: "fas fa-upload"
                    }), React.createElement("span", {
                      className: "ml-2 truncate"
                    }, imageLabel(imageName, selectedImageName))), React.createElement(School__InputGroupError.make, {
                  message: errorMessage,
                  active: errorState
                }));
}

var make = SchoolCustomize__ImageFileInput;

exports.str = str;
exports.imageLabel = imageLabel;
exports.make = make;
/* react Not a pure module */
