// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ArrayUtils = require("../../../shared/utils/ArrayUtils.bs.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function decode(json) {
  return {
          id: Json_decode.field("id", Json_decode.string, json),
          name: Json_decode.field("name", Json_decode.string, json),
          number: Json_decode.field("number", Json_decode.$$int, json)
        };
}

function id(t) {
  return t.id;
}

function name(t) {
  return t.name;
}

function number(t) {
  return t.number;
}

function sort(levels) {
  return ArrayUtils.copyAndSort((function (x, y) {
                return x.number - y.number | 0;
              }), levels);
}

function unsafeLevelNumber(levels, componentName, levelId) {
  return "Level " + String(ArrayUtils.unsafeFind((function (l) {
                    return l.id === levelId;
                  }), "Unable to find level with id: " + (levelId + ("in CoursesRevew__" + componentName)), levels).number);
}

exports.decode = decode;
exports.id = id;
exports.name = name;
exports.number = number;
exports.sort = sort;
exports.unsafeLevelNumber = unsafeLevelNumber;
/* ArrayUtils Not a pure module */
