// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function id(t) {
  return t.id;
}

function teamId(t) {
  return t.teamId;
}

function name(t) {
  return t.name;
}

function avatarUrl(t) {
  return t.avatarUrl;
}

function decode(json) {
  return {
          id: Json_decode.field("id", Json_decode.string, json),
          name: Json_decode.field("name", Json_decode.string, json),
          avatarUrl: Json_decode.field("avatarUrl", Json_decode.string, json),
          teamId: Json_decode.field("teamId", Json_decode.string, json)
        };
}

exports.id = id;
exports.name = name;
exports.avatarUrl = avatarUrl;
exports.teamId = teamId;
exports.decode = decode;
/* No side effect */
